language: csharp  
dist: bionic  
dotnet: 3.1
mono: none

branches:
  only:
  - master
  - release

script:  
  - bash "${TRAVIS_BUILD_DIR}/build/build.sh"

deploy:
  provider: script
  script: bash "${TRAVIS_BUILD_DIR}/build/build.sh" deploy
  skip_cleanup: true
  on:
    branch: release